/*
 * Copyright (c) 2025 OpenHarmonyPCDeveloper
 *
 * Licensed under the Mulan PSL v2 (the "License");
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *
 *          http://license.coscl.org.cn/MulanPSL2
 *
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */

export class OpenSourceNoticeMetaData {
  name: string = '';
  license: string = '';
  source: string = '';
  licenseFile: string = '';
  showLicense: boolean = false;
  isNeedHide?: boolean = false;
}
