/*
 * Copyright (c) 2025 OpenHarmonyPCDeveloper
 *
 * Licensed under the Mulan PSL v2 (the "License");
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *
 *          http://license.coscl.org.cn/MulanPSL2
 *
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */

import { OpenSourceNoticeMetaData } from './opensource_info'

const ossComponentsList: OpenSourceNoticeMetaData[] = [
  {
    "name": "autoconf",
    "license": "GPLv3",
    "source": "https://savannah.gnu.org/projects/autoconf",
    "licenseFile": "about_autoconf_opensource.html",
    "showLicense": false
  },
  {
    "name": "bind",
    "license": "GPLv3",
    "source": "https://www.isc.org/bind/",
    "licenseFile": "about_bind_opensource.html",
    "showLicense": false
  },
  {
    "name": "binutils",
    "license": "GPLv3",
    "source": "https://www.gnu.org/software/binutils/",
    "licenseFile": "about_binutils_opensource.html",
    "showLicense": false
  },
  {
    "name": "busybox",
    "license": "GPLv2",
    "source": "https://busybox.net/",
    "licenseFile": "about_busybox_opensource.html",
    "showLicense": false
  },
  {
    "name": "bzip2",
    "license": "BSD-like",
    "source": "https://sourceware.org/bzip2/",
    "licenseFile": "about_bzip2_opensource.html",
    "showLicense": false
  },
  {
    "name": "cmake",
    "license": "BSD-3-Clause",
    "source": "https://cmake.org/",
    "licenseFile": "about_cmake_opensource.html",
    "showLicense": false
  },
  {
    "name": "colrm",
    "license": "BSD-3-Clause",
    "source": "https://github.com/util-linux/util-linux",
    "licenseFile": "about_colrm_opensource.html",
    "showLicense": false
  },
  {
    "name": "column",
    "license": "BSD-3-Clause",
    "source": "https://github.com/util-linux/util-linux",
    "licenseFile": "about_column_opensource.html",
    "showLicense": false
  },
  {
    "name": "diffutils",
    "license": "GPLv3",
    "source": "https://www.gnu.org/software/diffutils/",
    "licenseFile": "about_diffutils_opensource.html",
    "showLicense": false
  },
  {
    "name": "expat",
    "license": "MIT",
    "source": "https://libexpat.github.io/",
    "licenseFile": "about_expat_opensource.html",
    "showLicense": false
  },
  {
    "name": "findutils",
    "license": "GPLv3",
    "source": "https://www.gnu.org/software/findutils/",
    "licenseFile": "about_findutils_opensource.html",
    "showLicense": false
  },
  {
    "name": "flex",
    "license": "BSD-2-Clause",
    "source": "https://github.com/westes/flex",
    "licenseFile": "about_flex_opensource.html",
    "showLicense": false
  },
  {
    "name": "gettext",
    "license": "GPLv3",
    "source": "https://www.gnu.org/software/gettext/",
    "licenseFile": "about_gettext_opensource.html",
    "showLicense": false
  },
  {
    "name": "gperf",
    "license": "GPLv3",
    "source": "https://www.gnu.org/software/gperf/",
    "licenseFile": "about_gperf_opensource.html",
    "showLicense": false
  },
  {
    "name": "gprof",
    "license": "GPLv3",
    "source": "https://sourceware.org/binutils/docs/gprof/",
    "licenseFile": "about_gprof_opensource.html",
    "showLicense": false
  },
  {
    "name": "grep",
    "license": "GPLv3",
    "source": "https://www.gnu.org/software/grep/",
    "licenseFile": "about_grep_opensource.html",
    "showLicense": false
  },
  {
    "name": "groff",
    "license": "GPLv3",
    "source": "https://www.gnu.org/software/groff/",
    "licenseFile": "about_groff_opensource.html",
    "showLicense": false
  },
  {
    "name": "gzip",
    "license": "GPLv3",
    "source": "https://www.gnu.org/software/gzip/",
    "licenseFile": "about_gzip_opensource.html",
    "showLicense": false
  },
  {
    "name": "less",
    "license": "GPLv3",
    "source": "https://www.greenwoodsoftware.com/less/",
    "licenseFile": "about_less_opensource.html",
    "showLicense": false
  },
  {
    "name": "libedit",
    "license": "BSD-3-Clause",
    "source": "https://thrysoee.dk/editline/",
    "licenseFile": "about_libedit_opensource.html",
    "showLicense": false
  },
  {
    "name": "libexpat",
    "license": "MIT",
    "source": "https://libexpat.github.io/",
    "licenseFile": "about_libexpat_opensource.html",
    "showLicense": false
  },
  {
    "name": "libffi",
    "license": "MIT",
    "source": "https://sourceware.org/libffi/",
    "licenseFile": "about_libffi_opensource.html",
    "showLicense": false
  },
  {
    "name": "libiconv",
    "license": "LGPLv2",
    "source": "https://www.gnu.org/software/libiconv/",
    "licenseFile": "about_libiconv_opensource.html",
    "showLicense": false
  },
  {
    "name": "libunistring",
    "license": "LGPLv3",
    "source": "https://www.gnu.org/software/libunistring/",
    "licenseFile": "about_libunistring_opensource.html",
    "showLicense": false
  },
  {
    "name": "libuv",
    "license": "MIT",
    "source": "https://github.com/libuv/libuv",
    "licenseFile": "about_libuv_opensource.html",
    "showLicense": false
  },
  {
    "name": "libxml",
    "license": "MIT",
    "source": "http://xmlsoft.org/",
    "licenseFile": "about_libxml_opensource.html",
    "showLicense": false
  },
  {
    "name": "libxslt",
    "license": "MIT",
    "source": "http://xmlsoft.org/libxslt/",
    "licenseFile": "about_libxslt_opensource.html",
    "showLicense": false
  },
  {
    "name": "libyaml",
    "license": "MIT",
    "source": "https://pyyaml.org/wiki/LibYAML",
    "licenseFile": "about_libyaml_opensource.html",
    "showLicense": false
  },
  {
    "name": "llvm",
    "license": "Apache-2.0",
    "source": "https://llvm.org/",
    "licenseFile": "about_llvm_opensource.html",
    "showLicense": false
  },
  {
    "name": "m4",
    "license": "GPLv3",
    "source": "https://www.gnu.org/software/m4/",
    "licenseFile": "about_m4_opensource.html",
    "showLicense": false
  },
  {
    "name": "make",
    "license": "GPLv3",
    "source": "https://www.gnu.org/software/make/",
    "licenseFile": "about_make_opensource.html",
    "showLicense": false
  },
  {
    "name": "ncurses",
    "license": "MIT",
    "source": "https://invisible-island.net/ncurses/",
    "licenseFile": "about_ncurses_opensource.html",
    "showLicense": false
  },
  {
    "name": "neovim",
    "license": "Apache-2.0",
    "source": "https://neovim.io/",
    "licenseFile": "about_neovim_opensource.html",
    "showLicense": false
  },
  {
    "name": "nghttp",
    "license": "MIT",
    "source": "https://nghttp2.org/",
    "licenseFile": "about_nghttp_opensource.html",
    "showLicense": false
  },
  {
    "name": "ninja",
    "license": "Apache-2.0",
    "source": "https://ninja-build.org/",
    "licenseFile": "about_ninja_opensource.html",
    "showLicense": false
  },
  {
    "name": "openssl",
    "license": "Apache-2.0",
    "source": "https://www.openssl.org/",
    "licenseFile": "about_openssl_opensource.html",
    "showLicense": false
  },
  {
    "name": "perl",
    "license": "GPLv1",
    "source": "https://www.perl.org/",
    "licenseFile": "about_perl_opensource.html",
    "showLicense": false
  },
  {
    "name": "ruby",
    "license": "BSD-2-Clause",
    "source": "https://www.ruby-lang.org/",
    "licenseFile": "about_ruby_opensource.html",
    "showLicense": false
  },
  {
    "name": "utils_linux",
    "license": "GPLv2",
    "source": "https://www.kernel.org/",
    "licenseFile": "about_utils_linux_opensource.html",
    "showLicense": false
  },
  {
    "name": "vim",
    "license": "GPLv2",
    "source": "https://www.vim.org/",
    "licenseFile": "about_vim_opensource.html",
    "showLicense": false
  },
  {
    "name": "whereis",
    "license": "GPLv3",
    "source": "https://www.gnu.org/software/findutils/",
    "licenseFile": "about_whereis_opensource.html",
    "showLicense": false
  },
  {
    "name": "xz",
    "license": "GPLv2",
    "source": "https://tukaani.org/xz/",
    "licenseFile": "about_xz_opensource.html",
    "showLicense": false
  },
  {
    "name": "zlib",
    "license": "zlib",
    "source": "https://zlib.net/",
    "licenseFile": "about_zlib_opensource.html",
    "showLicense": false
  }
]

export default ossComponentsList;